"""
Indian Food Database with Nutritional Information
Data sourced from Indian Food Composition Tables (IFCT) and NIN guidelines
"""

INDIAN_FOODS = [
    # ==================== GRAINS & CEREALS ====================
    {
        "name": "Rice (Cooked)",
        "name_hindi": "Chawal",
        "category": "grain",
        "calories": 130,
        "protein_g": 2.7,
        "carbs_g": 28,
        "fat_g": 0.3,
        "fiber_g": 0.4,
        "calcium_mg": 10,
        "iron_mg": 0.2,
        "zinc_mg": 0.5,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 3,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Cook until very soft, mash slightly for younger toddlers",
        "preparation_tips": "Use 1:2 rice to water ratio for softer texture",
        "serving_size_6_12": 30,
        "serving_size_12_24": 50,
        "serving_size_24_36": 75
    },
    {
        "name": "Roti/Chapati",
        "name_hindi": "Roti",
        "category": "grain",
        "calories": 240,
        "protein_g": 8,
        "carbs_g": 50,
        "fat_g": 1,
        "fiber_g": 4,
        "calcium_mg": 30,
        "iron_mg": 2.5,
        "zinc_mg": 1.5,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 20,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["gluten"],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Tear into small pieces, soften with dal or ghee",
        "preparation_tips": "Make softer rotis with milk instead of water",
        "serving_size_6_12": 15,
        "serving_size_12_24": 30,
        "serving_size_24_36": 50
    },
    {
        "name": "Paratha (Plain)",
        "name_hindi": "Paratha",
        "category": "grain",
        "calories": 300,
        "protein_g": 7,
        "carbs_g": 45,
        "fat_g": 10,
        "fiber_g": 3,
        "calcium_mg": 25,
        "iron_mg": 2,
        "zinc_mg": 1.2,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 18,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["gluten", "dairy"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Cut into small triangles, use less oil/ghee",
        "preparation_tips": "Stuff with mashed vegetables for extra nutrition"
    },
    {
        "name": "Idli",
        "name_hindi": "Idli",
        "category": "grain",
        "calories": 58,
        "protein_g": 2,
        "carbs_g": 12,
        "fat_g": 0.1,
        "fiber_g": 0.5,
        "calcium_mg": 5,
        "iron_mg": 0.4,
        "zinc_mg": 0.3,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 10,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Naturally soft, serve with mild sambar or coconut chutney",
        "preparation_tips": "Easy to digest due to fermentation. Add vegetables to batter for extra nutrition.",
        "serving_size_6_12": 30,
        "serving_size_12_24": 60,
        "serving_size_24_36": 90
    },
    {
        "name": "Dosa (Plain)",
        "name_hindi": "Dosa",
        "category": "grain",
        "calories": 133,
        "protein_g": 4,
        "carbs_g": 22,
        "fat_g": 3.5,
        "fiber_g": 1,
        "calcium_mg": 15,
        "iron_mg": 0.8,
        "zinc_mg": 0.5,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 15,
        "spice_level": 0,
        "texture": "regular",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Make soft dosas (not crispy), cut into strips",
        "preparation_tips": "Use less oil, serve with mild sambar"
    },
    {
        "name": "Upma",
        "name_hindi": "Upma",
        "category": "grain",
        "calories": 150,
        "protein_g": 4,
        "carbs_g": 25,
        "fat_g": 4,
        "fiber_g": 2,
        "calcium_mg": 15,
        "iron_mg": 1,
        "zinc_mg": 0.5,
        "vitamin_a_mcg": 20,
        "vitamin_c_mg": 5,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 12,
        "spice_level": 1,
        "texture": "soft",
        "allergens": ["gluten"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Skip mustard seeds and green chillies, add more vegetables",
        "preparation_tips": "Cook softer than adult version, add peas and carrots"
    },
    {
        "name": "Poha",
        "name_hindi": "Poha",
        "category": "grain",
        "calories": 180,
        "protein_g": 3.5,
        "carbs_g": 32,
        "fat_g": 5,
        "fiber_g": 1.5,
        "calcium_mg": 12,
        "iron_mg": 1.2,
        "zinc_mg": 0.6,
        "vitamin_a_mcg": 10,
        "vitamin_c_mg": 3,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 10,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Skip green chillies, reduce tempering",
        "preparation_tips": "Add peanut powder for protein if no nut allergy"
    },
    {
        "name": "Khichdi",
        "name_hindi": "Khichdi",
        "category": "grain",
        "calories": 120,
        "protein_g": 5,
        "carbs_g": 22,
        "fat_g": 2,
        "fiber_g": 2,
        "calcium_mg": 20,
        "iron_mg": 1.5,
        "zinc_mg": 0.8,
        "vitamin_a_mcg": 15,
        "vitamin_c_mg": 2,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 25,
        "spice_level": 0,
        "texture": "mashed",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Already toddler-friendly! Add vegetables and ghee",
        "preparation_tips": "Perfect first food. Add turmeric for immunity. Cook very soft."
    },
    {
        "name": "Ragi/Finger Millet Porridge",
        "name_hindi": "Ragi Kanji",
        "category": "grain",
        "calories": 140,
        "protein_g": 4,
        "carbs_g": 28,
        "fat_g": 1.5,
        "fiber_g": 4,
        "calcium_mg": 350,
        "iron_mg": 4,
        "zinc_mg": 2.5,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 18,
        "spice_level": 0,
        "texture": "puree",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Excellent first food - high in calcium and iron",
        "preparation_tips": "Mix with milk, add jaggery or mashed banana for sweetness"
    },
    {
        "name": "Daliya/Broken Wheat Porridge",
        "name_hindi": "Daliya",
        "category": "grain",
        "calories": 130,
        "protein_g": 5,
        "carbs_g": 26,
        "fat_g": 1,
        "fiber_g": 5,
        "calcium_mg": 20,
        "iron_mg": 1.8,
        "zinc_mg": 1,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 15,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["gluten"],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Cook very soft, make sweet with milk and jaggery or savory with vegetables",
        "preparation_tips": "Great fiber source. Soak before cooking for softer texture."
    },
    {
        "name": "Oats Porridge",
        "name_hindi": "Oats",
        "category": "grain",
        "calories": 150,
        "protein_g": 5,
        "carbs_g": 27,
        "fat_g": 3,
        "fiber_g": 4,
        "calcium_mg": 50,
        "iron_mg": 2,
        "zinc_mg": 1.5,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 20,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["gluten"],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Cook with milk, add mashed fruits",
        "preparation_tips": "Use rolled oats, not instant. Add banana or apple puree."
    },
    
    # ==================== DALS & LEGUMES ====================
    {
        "name": "Moong Dal",
        "name_hindi": "Moong Dal",
        "category": "dal",
        "calories": 105,
        "protein_g": 7,
        "carbs_g": 18,
        "fat_g": 0.5,
        "fiber_g": 5,
        "calcium_mg": 40,
        "iron_mg": 2.5,
        "zinc_mg": 1.5,
        "vitamin_a_mcg": 15,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 150,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Best first dal - easily digestible. Skip tempering, just add turmeric and salt",
        "preparation_tips": "Pressure cook until very soft. Add ghee for calories."
    },
    {
        "name": "Toor Dal",
        "name_hindi": "Arhar Dal",
        "category": "dal",
        "calories": 115,
        "protein_g": 7.5,
        "carbs_g": 20,
        "fat_g": 0.5,
        "fiber_g": 5,
        "calcium_mg": 45,
        "iron_mg": 2.8,
        "zinc_mg": 1.6,
        "vitamin_a_mcg": 10,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 140,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Skip tadka/tempering with chillies, use mild spices only",
        "preparation_tips": "Good protein source. Mix with rice for complete protein."
    },
    {
        "name": "Masoor Dal",
        "name_hindi": "Masoor Dal",
        "category": "dal",
        "calories": 110,
        "protein_g": 8,
        "carbs_g": 18,
        "fat_g": 0.5,
        "fiber_g": 4,
        "calcium_mg": 35,
        "iron_mg": 3,
        "zinc_mg": 1.8,
        "vitamin_a_mcg": 10,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 160,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "High in iron! Serve with vitamin C rich foods for absorption",
        "preparation_tips": "Cooks quickly. Pairs well with lemon juice."
    },
    {
        "name": "Chana Dal",
        "name_hindi": "Chana Dal",
        "category": "dal",
        "calories": 120,
        "protein_g": 8,
        "carbs_g": 20,
        "fat_g": 1,
        "fiber_g": 5,
        "calcium_mg": 50,
        "iron_mg": 2.5,
        "zinc_mg": 2,
        "vitamin_a_mcg": 15,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 130,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Needs more cooking time. Mash well for younger toddlers.",
        "preparation_tips": "Soak overnight for easier cooking and digestion."
    },
    {
        "name": "Rajma (Kidney Beans)",
        "name_hindi": "Rajma",
        "category": "dal",
        "calories": 125,
        "protein_g": 9,
        "carbs_g": 22,
        "fat_g": 0.5,
        "fiber_g": 6,
        "calcium_mg": 60,
        "iron_mg": 3,
        "zinc_mg": 2,
        "vitamin_a_mcg": 5,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 120,
        "spice_level": 2,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Mash some beans, reduce spices, skip whole chillies",
        "preparation_tips": "Must be well-cooked. High protein vegetarian option."
    },
    {
        "name": "Chole/Chickpeas",
        "name_hindi": "Chole",
        "category": "dal",
        "calories": 130,
        "protein_g": 8,
        "carbs_g": 22,
        "fat_g": 2,
        "fiber_g": 6,
        "calcium_mg": 55,
        "iron_mg": 2.8,
        "zinc_mg": 2,
        "vitamin_a_mcg": 10,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 170,
        "spice_level": 2,
        "texture": "regular",
        "allergens": [],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Mash or blend some chickpeas, reduce masala, skip whole spices",
        "preparation_tips": "High in folate. Remove skins for easier digestion."
    },
    {
        "name": "Sambar",
        "name_hindi": "Sambar",
        "category": "dal",
        "calories": 80,
        "protein_g": 4,
        "carbs_g": 12,
        "fat_g": 2,
        "fiber_g": 3,
        "calcium_mg": 35,
        "iron_mg": 1.5,
        "zinc_mg": 1,
        "vitamin_a_mcg": 100,
        "vitamin_c_mg": 8,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 80,
        "spice_level": 2,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Make mild sambar - skip red chillies, use less sambar powder",
        "preparation_tips": "Great with idli/dosa. Add lots of vegetables."
    },
    
    # ==================== VEGETABLES ====================
    {
        "name": "Potato (Boiled/Mashed)",
        "name_hindi": "Aloo",
        "category": "vegetable",
        "calories": 77,
        "protein_g": 2,
        "carbs_g": 17,
        "fat_g": 0.1,
        "fiber_g": 2,
        "calcium_mg": 12,
        "iron_mg": 0.8,
        "zinc_mg": 0.3,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 20,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 15,
        "spice_level": 0,
        "texture": "mashed",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Boil and mash with ghee. Good first food.",
        "preparation_tips": "Avoid fried preparations. Steam or boil preferred."
    },
    {
        "name": "Sweet Potato",
        "name_hindi": "Shakarkandi",
        "category": "vegetable",
        "calories": 86,
        "protein_g": 1.5,
        "carbs_g": 20,
        "fat_g": 0.1,
        "fiber_g": 3,
        "calcium_mg": 30,
        "iron_mg": 0.6,
        "zinc_mg": 0.3,
        "vitamin_a_mcg": 710,
        "vitamin_c_mg": 20,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 10,
        "spice_level": 0,
        "texture": "mashed",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Excellent first food! Very high in Vitamin A. Bake or steam and mash.",
        "preparation_tips": "Naturally sweet, no need to add sugar."
    },
    {
        "name": "Carrot",
        "name_hindi": "Gajar",
        "category": "vegetable",
        "calories": 41,
        "protein_g": 1,
        "carbs_g": 10,
        "fat_g": 0.2,
        "fiber_g": 3,
        "calcium_mg": 33,
        "iron_mg": 0.3,
        "zinc_mg": 0.2,
        "vitamin_a_mcg": 835,
        "vitamin_c_mg": 6,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 19,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Steam until soft, mash or cut into small pieces",
        "preparation_tips": "High in Vitamin A. Cook well for younger toddlers to prevent choking."
    },
    {
        "name": "Spinach/Palak",
        "name_hindi": "Palak",
        "category": "vegetable",
        "calories": 23,
        "protein_g": 2.9,
        "carbs_g": 3.6,
        "fat_g": 0.4,
        "fiber_g": 2.2,
        "calcium_mg": 99,
        "iron_mg": 2.7,
        "zinc_mg": 0.5,
        "vitamin_a_mcg": 470,
        "vitamin_c_mg": 28,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 195,
        "spice_level": 0,
        "texture": "puree",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Blend into dal, paratha stuffing, or make palak paneer (mild)",
        "preparation_tips": "High in iron and folate. Pair with vitamin C for iron absorption."
    },
    {
        "name": "Bottle Gourd/Lauki",
        "name_hindi": "Lauki/Ghiya",
        "category": "vegetable",
        "calories": 14,
        "protein_g": 0.6,
        "carbs_g": 3,
        "fat_g": 0.1,
        "fiber_g": 0.5,
        "calcium_mg": 20,
        "iron_mg": 0.2,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 5,
        "vitamin_c_mg": 10,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 6,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Very easy to digest. Mash well. Add to khichdi.",
        "preparation_tips": "Light and hydrating. Good for upset tummies."
    },
    {
        "name": "Pumpkin",
        "name_hindi": "Kaddu",
        "category": "vegetable",
        "calories": 26,
        "protein_g": 1,
        "carbs_g": 6,
        "fat_g": 0.1,
        "fiber_g": 0.5,
        "calcium_mg": 21,
        "iron_mg": 0.8,
        "zinc_mg": 0.3,
        "vitamin_a_mcg": 430,
        "vitamin_c_mg": 9,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 16,
        "spice_level": 0,
        "texture": "mashed",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Steam and mash. Naturally sweet. Excellent first food.",
        "preparation_tips": "High in Vitamin A. Mix with rice or dal."
    },
    {
        "name": "Peas",
        "name_hindi": "Matar",
        "category": "vegetable",
        "calories": 81,
        "protein_g": 5,
        "carbs_g": 14,
        "fat_g": 0.4,
        "fiber_g": 5,
        "calcium_mg": 25,
        "iron_mg": 1.5,
        "zinc_mg": 1.2,
        "vitamin_a_mcg": 38,
        "vitamin_c_mg": 40,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 65,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Mash or blend for younger toddlers to prevent choking",
        "preparation_tips": "Good protein and fiber source. Add to pulao, paratha, or upma."
    },
    {
        "name": "Beetroot",
        "name_hindi": "Chukandar",
        "category": "vegetable",
        "calories": 43,
        "protein_g": 1.6,
        "carbs_g": 10,
        "fat_g": 0.2,
        "fiber_g": 2.8,
        "calcium_mg": 16,
        "iron_mg": 0.8,
        "zinc_mg": 0.4,
        "vitamin_a_mcg": 2,
        "vitamin_c_mg": 5,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 110,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Steam and mash. Makes food colorful and appealing.",
        "preparation_tips": "High in folate. Can stain - use a bib!"
    },
    {
        "name": "Beans/French Beans",
        "name_hindi": "Sem/Beans",
        "category": "vegetable",
        "calories": 31,
        "protein_g": 1.8,
        "carbs_g": 7,
        "fat_g": 0.1,
        "fiber_g": 3,
        "calcium_mg": 37,
        "iron_mg": 1,
        "zinc_mg": 0.2,
        "vitamin_a_mcg": 35,
        "vitamin_c_mg": 12,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 33,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Steam until soft, cut into small pieces",
        "preparation_tips": "Good fiber source. Avoid giving whole to young toddlers."
    },
    {
        "name": "Brinjal/Eggplant",
        "name_hindi": "Baingan",
        "category": "vegetable",
        "calories": 25,
        "protein_g": 1,
        "carbs_g": 6,
        "fat_g": 0.2,
        "fiber_g": 3,
        "calcium_mg": 9,
        "iron_mg": 0.2,
        "zinc_mg": 0.2,
        "vitamin_a_mcg": 2,
        "vitamin_c_mg": 2,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 22,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Roast/bake and mash (baingan bharta style, mild)",
        "preparation_tips": "Remove skin for younger toddlers."
    },
    {
        "name": "Cauliflower",
        "name_hindi": "Gobhi",
        "category": "vegetable",
        "calories": 25,
        "protein_g": 2,
        "carbs_g": 5,
        "fat_g": 0.3,
        "fiber_g": 2,
        "calcium_mg": 22,
        "iron_mg": 0.4,
        "zinc_mg": 0.3,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 48,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 57,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Steam until very soft, cut into small florets",
        "preparation_tips": "High in Vitamin C. Can cause gas - introduce gradually."
    },
    {
        "name": "Tomato",
        "name_hindi": "Tamatar",
        "category": "vegetable",
        "calories": 18,
        "protein_g": 0.9,
        "carbs_g": 4,
        "fat_g": 0.2,
        "fiber_g": 1.2,
        "calcium_mg": 10,
        "iron_mg": 0.3,
        "zinc_mg": 0.2,
        "vitamin_a_mcg": 42,
        "vitamin_c_mg": 14,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 15,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Remove skin and seeds, cook well",
        "preparation_tips": "Acidic - some toddlers may get rashes. Introduce carefully."
    },
    
    # ==================== FRUITS ====================
    {
        "name": "Banana",
        "name_hindi": "Kela",
        "category": "fruit",
        "calories": 89,
        "protein_g": 1.1,
        "carbs_g": 23,
        "fat_g": 0.3,
        "fiber_g": 2.6,
        "calcium_mg": 5,
        "iron_mg": 0.3,
        "zinc_mg": 0.2,
        "vitamin_a_mcg": 3,
        "vitamin_c_mg": 9,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 20,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Mash for young babies, give whole/sliced for older toddlers",
        "preparation_tips": "Perfect first fruit. High energy, easy to digest."
    },
    {
        "name": "Apple",
        "name_hindi": "Seb",
        "category": "fruit",
        "calories": 52,
        "protein_g": 0.3,
        "carbs_g": 14,
        "fat_g": 0.2,
        "fiber_g": 2.4,
        "calcium_mg": 6,
        "iron_mg": 0.1,
        "zinc_mg": 0,
        "vitamin_a_mcg": 3,
        "vitamin_c_mg": 5,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 3,
        "spice_level": 0,
        "texture": "regular",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Steam and mash for babies, grate or slice thin for toddlers",
        "preparation_tips": "Good fiber source. Raw apple can be a choking hazard - prepare appropriately."
    },
    {
        "name": "Mango",
        "name_hindi": "Aam",
        "category": "fruit",
        "calories": 60,
        "protein_g": 0.8,
        "carbs_g": 15,
        "fat_g": 0.4,
        "fiber_g": 1.6,
        "calcium_mg": 11,
        "iron_mg": 0.2,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 54,
        "vitamin_c_mg": 36,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 43,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Ripe mango puree. Very sweet - give in moderation.",
        "preparation_tips": "High in Vitamin A and C. Seasonal treat."
    },
    {
        "name": "Papaya",
        "name_hindi": "Papita",
        "category": "fruit",
        "calories": 43,
        "protein_g": 0.5,
        "carbs_g": 11,
        "fat_g": 0.3,
        "fiber_g": 1.7,
        "calcium_mg": 20,
        "iron_mg": 0.3,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 47,
        "vitamin_c_mg": 60,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 37,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Ripe papaya is naturally soft. Mash or cube.",
        "preparation_tips": "Aids digestion. High in Vitamin C. Avoid unripe papaya."
    },
    {
        "name": "Chikoo/Sapota",
        "name_hindi": "Chikoo",
        "category": "fruit",
        "calories": 83,
        "protein_g": 0.4,
        "carbs_g": 20,
        "fat_g": 1.1,
        "fiber_g": 5.3,
        "calcium_mg": 21,
        "iron_mg": 0.8,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 6,
        "vitamin_c_mg": 15,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 14,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Very ripe chikoo mashed. Good for weight gain.",
        "preparation_tips": "Remove seeds carefully - choking hazard."
    },
    {
        "name": "Pomegranate",
        "name_hindi": "Anar",
        "category": "fruit",
        "calories": 83,
        "protein_g": 1.7,
        "carbs_g": 19,
        "fat_g": 1.2,
        "fiber_g": 4,
        "calcium_mg": 10,
        "iron_mg": 0.3,
        "zinc_mg": 0.4,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 10,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 38,
        "spice_level": 0,
        "texture": "regular",
        "allergens": [],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Give juice or supervise closely - seeds can choke",
        "preparation_tips": "Rich in antioxidants. Give as juice for younger toddlers."
    },
    {
        "name": "Grapes",
        "name_hindi": "Angoor",
        "category": "fruit",
        "calories": 69,
        "protein_g": 0.7,
        "carbs_g": 18,
        "fat_g": 0.2,
        "fiber_g": 0.9,
        "calcium_mg": 10,
        "iron_mg": 0.4,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 3,
        "vitamin_c_mg": 11,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 2,
        "spice_level": 0,
        "texture": "regular",
        "allergens": [],
        "suitable_from_months": 12,
        "toddler_friendly_version": "MUST cut into quarters lengthwise - major choking hazard whole",
        "preparation_tips": "Always cut grapes for toddlers under 4 years."
    },
    {
        "name": "Orange",
        "name_hindi": "Santra",
        "category": "fruit",
        "calories": 47,
        "protein_g": 0.9,
        "carbs_g": 12,
        "fat_g": 0.1,
        "fiber_g": 2.4,
        "calcium_mg": 40,
        "iron_mg": 0.1,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 11,
        "vitamin_c_mg": 53,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 30,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Remove membranes and seeds, give segments",
        "preparation_tips": "High Vitamin C helps iron absorption. Acidic - may cause rash around mouth."
    },
    {
        "name": "Watermelon",
        "name_hindi": "Tarbooz",
        "category": "fruit",
        "calories": 30,
        "protein_g": 0.6,
        "carbs_g": 8,
        "fat_g": 0.2,
        "fiber_g": 0.4,
        "calcium_mg": 7,
        "iron_mg": 0.2,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 28,
        "vitamin_c_mg": 8,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 3,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Remove all seeds, cut into small pieces",
        "preparation_tips": "Hydrating summer fruit. Low calories."
    },
    
    # ==================== DAIRY ====================
    {
        "name": "Milk (Whole)",
        "name_hindi": "Doodh",
        "category": "dairy",
        "calories": 61,
        "protein_g": 3.2,
        "carbs_g": 4.8,
        "fat_g": 3.3,
        "fiber_g": 0,
        "calcium_mg": 120,
        "iron_mg": 0.1,
        "zinc_mg": 0.4,
        "vitamin_a_mcg": 46,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 1,
        "vitamin_b12_mcg": 0.5,
        "folate_mcg": 5,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["dairy"],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Full fat milk recommended for toddlers. Can give warm or cold.",
        "preparation_tips": "Don't replace breast/formula with cow milk before 12 months."
    },
    {
        "name": "Curd/Yogurt",
        "name_hindi": "Dahi",
        "category": "dairy",
        "calories": 60,
        "protein_g": 3.5,
        "carbs_g": 4.7,
        "fat_g": 3.3,
        "fiber_g": 0,
        "calcium_mg": 150,
        "iron_mg": 0.1,
        "zinc_mg": 0.6,
        "vitamin_a_mcg": 27,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 0.1,
        "vitamin_b12_mcg": 0.5,
        "folate_mcg": 12,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["dairy"],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Plain, unsweetened curd. Can mix with fruits or rice.",
        "preparation_tips": "Probiotic benefits. Easier to digest than milk for some babies."
    },
    {
        "name": "Paneer",
        "name_hindi": "Paneer",
        "category": "dairy",
        "calories": 265,
        "protein_g": 18,
        "carbs_g": 1.2,
        "fat_g": 21,
        "fiber_g": 0,
        "calcium_mg": 208,
        "iron_mg": 0.2,
        "zinc_mg": 0.5,
        "vitamin_a_mcg": 180,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0.3,
        "vitamin_b12_mcg": 0.8,
        "folate_mcg": 37,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["dairy"],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Cut into small cubes, give plain or lightly spiced",
        "preparation_tips": "Excellent protein source. Can be mashed for younger babies."
    },
    {
        "name": "Cheese",
        "name_hindi": "Cheese",
        "category": "dairy",
        "calories": 350,
        "protein_g": 22,
        "carbs_g": 2,
        "fat_g": 28,
        "fiber_g": 0,
        "calcium_mg": 720,
        "iron_mg": 0.3,
        "zinc_mg": 3,
        "vitamin_a_mcg": 260,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0.3,
        "vitamin_b12_mcg": 1.1,
        "folate_mcg": 20,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["dairy"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Choose mild cheese, grate or cut into small pieces",
        "preparation_tips": "High in calcium and protein. Watch sodium content."
    },
    {
        "name": "Ghee",
        "name_hindi": "Ghee",
        "category": "dairy",
        "calories": 900,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 100,
        "fiber_g": 0,
        "calcium_mg": 0,
        "iron_mg": 0,
        "zinc_mg": 0,
        "vitamin_a_mcg": 450,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 0,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["dairy"],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Add 1/2-1 tsp to dal, rice, khichdi",
        "preparation_tips": "Good fat source for brain development. Essential for vegetarian toddlers.",
        "serving_size_6_12": 5,
        "serving_size_12_24": 8,
        "serving_size_24_36": 10
    },
    {
        "name": "Buttermilk/Chaas",
        "name_hindi": "Chaas/Mattha",
        "category": "dairy",
        "calories": 40,
        "protein_g": 3,
        "carbs_g": 5,
        "fat_g": 1,
        "fiber_g": 0,
        "calcium_mg": 120,
        "iron_mg": 0.1,
        "zinc_mg": 0.4,
        "vitamin_a_mcg": 20,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0.4,
        "folate_mcg": 10,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["dairy"],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Skip salt and spices. Plain buttermilk only.",
        "preparation_tips": "Cooling and probiotic. Good for digestion."
    },
    
    # ==================== PROTEIN (NON-VEG) ====================
    {
        "name": "Egg (Boiled)",
        "name_hindi": "Anda",
        "category": "protein",
        "calories": 155,
        "protein_g": 13,
        "carbs_g": 1.1,
        "fat_g": 11,
        "fiber_g": 0,
        "calcium_mg": 56,
        "iron_mg": 1.8,
        "zinc_mg": 1.3,
        "vitamin_a_mcg": 160,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 2,
        "vitamin_b12_mcg": 1.1,
        "folate_mcg": 47,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["egg"],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Hard boil, mash yolk first. Introduce white separately.",
        "preparation_tips": "Complete protein. Yolk is rich in iron and B12."
    },
    {
        "name": "Chicken (Boneless)",
        "name_hindi": "Murgh",
        "category": "protein",
        "calories": 165,
        "protein_g": 31,
        "carbs_g": 0,
        "fat_g": 3.6,
        "fiber_g": 0,
        "calcium_mg": 15,
        "iron_mg": 1,
        "zinc_mg": 1.3,
        "vitamin_a_mcg": 6,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0.1,
        "vitamin_b12_mcg": 0.3,
        "folate_mcg": 4,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Boil or steam, shred finely. Avoid fried preparations.",
        "preparation_tips": "High quality protein. Ensure no bones."
    },
    {
        "name": "Fish (Rohu/Pomfret)",
        "name_hindi": "Machli",
        "category": "protein",
        "calories": 95,
        "protein_g": 19,
        "carbs_g": 0,
        "fat_g": 2,
        "fiber_g": 0,
        "calcium_mg": 60,
        "iron_mg": 0.5,
        "zinc_mg": 0.8,
        "vitamin_a_mcg": 15,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 10,
        "vitamin_b12_mcg": 2,
        "folate_mcg": 12,
        "spice_level": 1,
        "texture": "soft",
        "allergens": ["fish"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Steam or bake, remove ALL bones carefully, flake finely",
        "preparation_tips": "Excellent source of Vitamin D and omega-3. Be very careful about bones."
    },
    
    # ==================== SNACKS & OTHERS ====================
    {
        "name": "Dates",
        "name_hindi": "Khajoor",
        "category": "snack",
        "calories": 277,
        "protein_g": 1.8,
        "carbs_g": 75,
        "fat_g": 0.2,
        "fiber_g": 7,
        "calcium_mg": 64,
        "iron_mg": 1,
        "zinc_mg": 0.4,
        "vitamin_a_mcg": 7,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 15,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Remove seed, mash or cut very small. Natural sweetener.",
        "preparation_tips": "Good source of iron. High in sugar - use sparingly.",
        "serving_size_6_12": 10,
        "serving_size_12_24": 15,
        "serving_size_24_36": 20
    },
    {
        "name": "Dry Fruits Mix (soaked)",
        "name_hindi": "Meva",
        "category": "snack",
        "calories": 570,
        "protein_g": 18,
        "carbs_g": 25,
        "fat_g": 45,
        "fiber_g": 10,
        "calcium_mg": 200,
        "iron_mg": 3.5,
        "zinc_mg": 3,
        "vitamin_a_mcg": 5,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 50,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["nuts"],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Soak overnight, grind to paste. Add to milk or porridge.",
        "preparation_tips": "High calorie, good for underweight toddlers. Check for nut allergies first.",
        "serving_size_6_12": 5,
        "serving_size_12_24": 10,
        "serving_size_24_36": 15
    },
    {
        "name": "Jaggery",
        "name_hindi": "Gur",
        "category": "snack",
        "calories": 383,
        "protein_g": 0.4,
        "carbs_g": 98,
        "fat_g": 0.1,
        "fiber_g": 0,
        "calcium_mg": 80,
        "iron_mg": 11,
        "zinc_mg": 0.2,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 0,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Use small amounts as natural sweetener instead of sugar",
        "preparation_tips": "Good source of iron. Better than refined sugar but still limit quantity.",
        "serving_size_6_12": 0,
        "serving_size_12_24": 5,
        "serving_size_24_36": 10
    },
    {
        "name": "Coconut (Fresh)",
        "name_hindi": "Nariyal",
        "category": "snack",
        "calories": 354,
        "protein_g": 3.3,
        "carbs_g": 15,
        "fat_g": 33,
        "fiber_g": 9,
        "calcium_mg": 14,
        "iron_mg": 2.4,
        "zinc_mg": 1.1,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 3,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 26,
        "spice_level": 0,
        "texture": "regular",
        "allergens": ["coconut"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Grate finely or give coconut water. Avoid large pieces.",
        "preparation_tips": "Good fat source. Coconut water is hydrating."
    },
    {
        "name": "Peanuts (Roasted)",
        "name_hindi": "Moongphali",
        "category": "snack",
        "calories": 567,
        "protein_g": 26,
        "carbs_g": 16,
        "fat_g": 49,
        "fiber_g": 8,
        "calcium_mg": 92,
        "iron_mg": 4.6,
        "zinc_mg": 3.3,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 240,
        "spice_level": 0,
        "texture": "crunchy",
        "allergens": ["peanuts"],
        "suitable_from_months": 12,
        "toddler_friendly_version": "ONLY as fine powder or butter - whole peanuts are choking hazard",
        "preparation_tips": "Introduce carefully, common allergen. Never give whole to toddlers."
    },
    {
        "name": "Ragi Biscuits/Cookies",
        "name_hindi": "Ragi Biscuit",
        "category": "snack",
        "calories": 420,
        "protein_g": 6,
        "carbs_g": 65,
        "fat_g": 15,
        "fiber_g": 4,
        "calcium_mg": 200,
        "iron_mg": 2.5,
        "zinc_mg": 1,
        "vitamin_a_mcg": 10,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 15,
        "spice_level": 0,
        "texture": "crunchy",
        "allergens": ["gluten"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Look for low sugar, whole grain options",
        "preparation_tips": "Good occasional snack. Choose homemade or healthy store brands."
    },
    
    # ==================== BEVERAGES ====================
    {
        "name": "Coconut Water",
        "name_hindi": "Nariyal Pani",
        "category": "beverage",
        "calories": 19,
        "protein_g": 0.7,
        "carbs_g": 3.7,
        "fat_g": 0.2,
        "fiber_g": 1.1,
        "calcium_mg": 24,
        "iron_mg": 0.3,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 0,
        "vitamin_c_mg": 2.4,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 3,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Fresh coconut water, avoid packaged with added sugar",
        "preparation_tips": "Natural electrolyte. Good for hydration."
    },
    {
        "name": "Fresh Fruit Juice (no sugar)",
        "name_hindi": "Fruit Juice",
        "category": "beverage",
        "calories": 45,
        "protein_g": 0.5,
        "carbs_g": 11,
        "fat_g": 0.1,
        "fiber_g": 0.2,
        "calcium_mg": 10,
        "iron_mg": 0.2,
        "zinc_mg": 0.1,
        "vitamin_a_mcg": 15,
        "vitamin_c_mg": 30,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 15,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Limit to 100ml/day. Whole fruits are better.",
        "preparation_tips": "Dilute with water. Too much juice reduces appetite for solid food."
    },
    
    # ==================== COMBO DISHES ====================
    {
        "name": "Dal Rice",
        "name_hindi": "Dal Chawal",
        "category": "combo",
        "calories": 180,
        "protein_g": 7,
        "carbs_g": 32,
        "fat_g": 2,
        "fiber_g": 3,
        "calcium_mg": 35,
        "iron_mg": 2,
        "zinc_mg": 1.2,
        "vitamin_a_mcg": 10,
        "vitamin_c_mg": 2,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 80,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 6,
        "toddler_friendly_version": "Mash together, add ghee. Skip tempering for babies.",
        "preparation_tips": "Complete protein when combined. Staple toddler meal."
    },
    {
        "name": "Vegetable Pulao",
        "name_hindi": "Pulao",
        "category": "combo",
        "calories": 160,
        "protein_g": 4,
        "carbs_g": 28,
        "fat_g": 4,
        "fiber_g": 2,
        "calcium_mg": 25,
        "iron_mg": 1,
        "zinc_mg": 0.8,
        "vitamin_a_mcg": 50,
        "vitamin_c_mg": 8,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 30,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Use mild spices, cut vegetables very small",
        "preparation_tips": "Good way to sneak in vegetables."
    },
    {
        "name": "Palak Paneer",
        "name_hindi": "Palak Paneer",
        "category": "combo",
        "calories": 200,
        "protein_g": 12,
        "carbs_g": 8,
        "fat_g": 14,
        "fiber_g": 3,
        "calcium_mg": 250,
        "iron_mg": 3,
        "zinc_mg": 1.5,
        "vitamin_a_mcg": 400,
        "vitamin_c_mg": 20,
        "vitamin_d_mcg": 0.2,
        "vitamin_b12_mcg": 0.4,
        "folate_mcg": 100,
        "spice_level": 2,
        "texture": "soft",
        "allergens": ["dairy"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Make mild version - no chillies, less garam masala",
        "preparation_tips": "Iron + protein powerhouse. Cut paneer small for toddlers."
    },
    {
        "name": "Aloo Paratha",
        "name_hindi": "Aloo Paratha",
        "category": "combo",
        "calories": 280,
        "protein_g": 6,
        "carbs_g": 40,
        "fat_g": 11,
        "fiber_g": 3,
        "calcium_mg": 30,
        "iron_mg": 2,
        "zinc_mg": 1,
        "vitamin_a_mcg": 5,
        "vitamin_c_mg": 10,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 25,
        "spice_level": 1,
        "texture": "soft",
        "allergens": ["gluten", "dairy"],
        "suitable_from_months": 12,
        "toddler_friendly_version": "Make filling mild (no chillies), cut into small pieces",
        "preparation_tips": "Serve with curd. Good for picky eaters."
    },
    {
        "name": "Curd Rice",
        "name_hindi": "Dahi Chawal",
        "category": "combo",
        "calories": 140,
        "protein_g": 5,
        "carbs_g": 25,
        "fat_g": 3,
        "fiber_g": 1,
        "calcium_mg": 120,
        "iron_mg": 0.5,
        "zinc_mg": 0.8,
        "vitamin_a_mcg": 25,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 0.1,
        "vitamin_b12_mcg": 0.3,
        "folate_mcg": 15,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["dairy"],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Perfect toddler food! Cooling and probiotic.",
        "preparation_tips": "Mash rice well. Add tiny bit of salt."
    },
    {
        "name": "Pongal",
        "name_hindi": "Pongal",
        "category": "combo",
        "calories": 150,
        "protein_g": 5,
        "carbs_g": 25,
        "fat_g": 4,
        "fiber_g": 2,
        "calcium_mg": 25,
        "iron_mg": 1.5,
        "zinc_mg": 1,
        "vitamin_a_mcg": 10,
        "vitamin_c_mg": 1,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 60,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 8,
        "toddler_friendly_version": "Reduce pepper, add more ghee",
        "preparation_tips": "South Indian comfort food. Easy to digest."
    },
    {
        "name": "Egg Bhurji",
        "name_hindi": "Anda Bhurji",
        "category": "combo",
        "calories": 180,
        "protein_g": 12,
        "carbs_g": 3,
        "fat_g": 14,
        "fiber_g": 0.5,
        "calcium_mg": 50,
        "iron_mg": 2,
        "zinc_mg": 1.2,
        "vitamin_a_mcg": 180,
        "vitamin_c_mg": 3,
        "vitamin_d_mcg": 1.5,
        "vitamin_b12_mcg": 1,
        "folate_mcg": 40,
        "spice_level": 2,
        "texture": "soft",
        "allergens": ["egg"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Skip chillies and onions initially, make plain scrambled eggs",
        "preparation_tips": "Quick protein meal. Add vegetables for variety."
    },
    {
        "name": "Mixed Vegetable Sabzi",
        "name_hindi": "Mix Sabzi",
        "category": "combo",
        "calories": 80,
        "protein_g": 3,
        "carbs_g": 12,
        "fat_g": 3,
        "fiber_g": 4,
        "calcium_mg": 40,
        "iron_mg": 1.2,
        "zinc_mg": 0.6,
        "vitamin_a_mcg": 200,
        "vitamin_c_mg": 15,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 45,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Cook until very soft, mash partially, mild spices only",
        "preparation_tips": "Great way to include multiple vegetables."
    },
    {
        "name": "Uttapam",
        "name_hindi": "Uttapam",
        "category": "combo",
        "calories": 166,
        "protein_g": 5,
        "carbs_g": 28,
        "fat_g": 4,
        "fiber_g": 2,
        "calcium_mg": 20,
        "iron_mg": 1,
        "zinc_mg": 0.6,
        "vitamin_a_mcg": 30,
        "vitamin_c_mg": 5,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 20,
        "spice_level": 0,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Top with finely chopped mild vegetables, cut into small pieces",
        "preparation_tips": "Thicker than dosa, easier for toddlers to hold."
    },
    {
        "name": "Besan Chilla",
        "name_hindi": "Besan Chilla",
        "category": "combo",
        "calories": 180,
        "protein_g": 8,
        "carbs_g": 20,
        "fat_g": 7,
        "fiber_g": 3,
        "calcium_mg": 40,
        "iron_mg": 2,
        "zinc_mg": 1.2,
        "vitamin_a_mcg": 20,
        "vitamin_c_mg": 5,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 50,
        "spice_level": 1,
        "texture": "soft",
        "allergens": [],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Make thin and soft, add finely grated vegetables",
        "preparation_tips": "High protein from besan. Gluten-free option."
    },
    {
        "name": "Suji Halwa",
        "name_hindi": "Suji Halwa",
        "category": "snack",
        "calories": 350,
        "protein_g": 5,
        "carbs_g": 45,
        "fat_g": 17,
        "fiber_g": 1,
        "calcium_mg": 30,
        "iron_mg": 1.5,
        "zinc_mg": 0.6,
        "vitamin_a_mcg": 150,
        "vitamin_c_mg": 0,
        "vitamin_d_mcg": 0,
        "vitamin_b12_mcg": 0,
        "folate_mcg": 20,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["gluten", "dairy"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Use less sugar, can use jaggery instead",
        "preparation_tips": "Occasional treat. High calorie for underweight toddlers."
    },
    {
        "name": "Banana Pancakes",
        "name_hindi": "Banana Pancake",
        "category": "snack",
        "calories": 150,
        "protein_g": 4,
        "carbs_g": 25,
        "fat_g": 4,
        "fiber_g": 2,
        "calcium_mg": 30,
        "iron_mg": 1,
        "zinc_mg": 0.5,
        "vitamin_a_mcg": 20,
        "vitamin_c_mg": 5,
        "vitamin_d_mcg": 0.3,
        "vitamin_b12_mcg": 0.2,
        "folate_mcg": 20,
        "spice_level": 0,
        "texture": "soft",
        "allergens": ["gluten", "egg"],
        "suitable_from_months": 10,
        "toddler_friendly_version": "Make with mashed banana, oats/flour, and egg. No added sugar.",
        "preparation_tips": "Healthy breakfast or snack option."
    },
]

# Allergen categories for easy filtering
COMMON_ALLERGENS = [
    "dairy",
    "egg",
    "peanuts",
    "tree_nuts",
    "gluten",
    "soy",
    "fish",
    "shellfish",
    "sesame",
    "coconut"
]

# Food categories
FOOD_CATEGORIES = [
    "grain",
    "dal",
    "vegetable",
    "fruit",
    "dairy",
    "protein",
    "snack",
    "beverage",
    "combo"
]

def get_foods_by_category(category):
    """Get all foods in a specific category"""
    return [f for f in INDIAN_FOODS if f["category"] == category]

def get_foods_suitable_for_age(age_months):
    """Get all foods suitable for a given age"""
    return [f for f in INDIAN_FOODS if f["suitable_from_months"] <= age_months]

def get_iron_rich_foods():
    """Get foods high in iron (>2mg per 100g)"""
    return [f for f in INDIAN_FOODS if f["iron_mg"] > 2]

def get_calcium_rich_foods():
    """Get foods high in calcium (>100mg per 100g)"""
    return [f for f in INDIAN_FOODS if f["calcium_mg"] > 100]

def get_protein_rich_foods():
    """Get foods high in protein (>10g per 100g)"""
    return [f for f in INDIAN_FOODS if f["protein_g"] > 10]

def search_foods(query):
    """Search foods by name (English or Hindi)"""
    query = query.lower()
    return [f for f in INDIAN_FOODS if query in f["name"].lower() or 
            (f.get("name_hindi") and query in f["name_hindi"].lower())]


def init_food_database(db_session, Food):
    """Initialize the food database with all Indian foods"""
    from sqlalchemy import inspect
    
    # Check if foods already exist
    if Food.query.count() > 0:
        return False
    
    for food_data in INDIAN_FOODS:
        food = Food(
            name=food_data["name"],
            name_hindi=food_data.get("name_hindi"),
            category=food_data["category"],
            calories=food_data["calories"],
            protein_g=food_data["protein_g"],
            carbs_g=food_data["carbs_g"],
            fat_g=food_data["fat_g"],
            fiber_g=food_data["fiber_g"],
            calcium_mg=food_data["calcium_mg"],
            iron_mg=food_data["iron_mg"],
            zinc_mg=food_data["zinc_mg"],
            vitamin_a_mcg=food_data["vitamin_a_mcg"],
            vitamin_c_mg=food_data["vitamin_c_mg"],
            vitamin_d_mcg=food_data.get("vitamin_d_mcg", 0),
            vitamin_b12_mcg=food_data.get("vitamin_b12_mcg", 0),
            folate_mcg=food_data.get("folate_mcg", 0),
            is_indian=True,
            spice_level=food_data["spice_level"],
            texture=food_data["texture"],
            allergens=food_data["allergens"],
            suitable_from_months=food_data["suitable_from_months"],
            toddler_friendly_version=food_data.get("toddler_friendly_version"),
            preparation_tips=food_data.get("preparation_tips"),
            serving_size_6_12=food_data.get("serving_size_6_12", 30),
            serving_size_12_24=food_data.get("serving_size_12_24", 50),
            serving_size_24_36=food_data.get("serving_size_24_36", 75)
        )
        db_session.add(food)
    
    db_session.commit()
    return True
