#!/usr/bin/env node
/**
 * Optionally bake a default server URL into the Android shell.
 * The app also lets you enter/change the URL on first launch.
 *
 * Usage:
 *   npm run configure -- https://your-littlebowl-host
 *   SERVER_URL=https://your-littlebowl-host npm run configure
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const configPath = path.join(root, 'capacitor.config.json');
const envPath = path.join(root, '.env');
const webConfigPath = path.join(root, 'www', 'config.js');

function readEnvFile() {
  if (!fs.existsSync(envPath)) return {};
  const out = {};
  for (const line of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    out[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  }
  return out;
}

function normalizeUrl(raw) {
  const url = String(raw || '').trim().replace(/\/+$/, '');
  if (!url) return null;
  if (!/^https?:\/\//i.test(url)) {
    throw new Error(`SERVER_URL must start with http:// or https:// (got: ${url})`);
  }
  return url;
}

const fromArg = process.argv[2];
const fromEnv = process.env.SERVER_URL || readEnvFile().SERVER_URL;
const serverUrl = normalizeUrl(fromArg || fromEnv);

if (!serverUrl) {
  console.error('Missing server URL.');
  console.error('Usage: npm run configure -- https://your-domain');
  console.error('   or: SERVER_URL=https://your-domain npm run configure');
  console.error('');
  console.error('You can also skip this and enter the URL inside the app on first launch.');
  process.exit(1);
}

// Keep Capacitor loading local www (setup + redirect). Do not set server.url,
// or the in-app setup screen would be skipped.
const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
if (config.server) delete config.server;
fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');

fs.writeFileSync(
  webConfigPath,
  `// Generated by npm run configure — default prefilled on first launch.\n` +
    `window.LITTLEBOWL_DEFAULT_SERVER = ${JSON.stringify(serverUrl)};\n`
);

fs.writeFileSync(
  envPath,
  `# LittleBowl Android shell\nSERVER_URL=${serverUrl}\n`
);

console.log(`Baked default server URL → ${serverUrl}`);
console.log('The app still shows setup if no URL has been saved on the device.');
console.log('Next: npm run sync');
